import { AppSidebar } from "@/app/_common/sidebar/app-sidebar"
import BreadCrumb from "@/app/_common/bread-crumb"
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"
import "@/app/globals.css";
import { ThemeProvider } from "../_common/theme/theme-provider";
// import Header from "../_common/header";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <BreadCrumb />

              {children}

            </SidebarInset>
          </SidebarProvider>


        </ThemeProvider>


      </body>
    </html>
  );
}
